// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: drone_control.proto

package grpcpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json  string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{0}
}

func (x *JsonResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *JsonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDronesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDronesRequest) Reset() {
	*x = GetDronesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDronesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDronesRequest) ProtoMessage() {}

func (x *GetDronesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDronesRequest.ProtoReflect.Descriptor instead.
func (*GetDronesRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{1}
}

type GetDroneStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDroneStatesRequest) Reset() {
	*x = GetDroneStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDroneStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDroneStatesRequest) ProtoMessage() {}

func (x *GetDroneStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDroneStatesRequest.ProtoReflect.Descriptor instead.
func (*GetDroneStatesRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{2}
}

type GetDroneDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DroneId int32 `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
}

func (x *GetDroneDetailRequest) Reset() {
	*x = GetDroneDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDroneDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDroneDetailRequest) ProtoMessage() {}

func (x *GetDroneDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDroneDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDroneDetailRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetDroneDetailRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

type FlightCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DroneId int32  `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *FlightCommandRequest) Reset() {
	*x = FlightCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightCommandRequest) ProtoMessage() {}

func (x *FlightCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightCommandRequest.ProtoReflect.Descriptor instead.
func (*FlightCommandRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{4}
}

func (x *FlightCommandRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *FlightCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type FlightCommandWithParamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DroneId    int32  `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Command    string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ParamsJson string `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
}

func (x *FlightCommandWithParamsRequest) Reset() {
	*x = FlightCommandWithParamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightCommandWithParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightCommandWithParamsRequest) ProtoMessage() {}

func (x *FlightCommandWithParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightCommandWithParamsRequest.ProtoReflect.Descriptor instead.
func (*FlightCommandWithParamsRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{5}
}

func (x *FlightCommandWithParamsRequest) GetDroneId() int32 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *FlightCommandWithParamsRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *FlightCommandWithParamsRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type AutoFlightRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AutoFlightRequestReq) Reset() {
	*x = AutoFlightRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoFlightRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoFlightRequestReq) ProtoMessage() {}

func (x *AutoFlightRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoFlightRequestReq.ProtoReflect.Descriptor instead.
func (*AutoFlightRequestReq) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{6}
}

type GetFlightStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFlightStatusRequest) Reset() {
	*x = GetFlightStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightStatusRequest) ProtoMessage() {}

func (x *GetFlightStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFlightStatusRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{7}
}

type EvaluateAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestJson string `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
}

func (x *EvaluateAccessRequest) Reset() {
	*x = EvaluateAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drone_control_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAccessRequest) ProtoMessage() {}

func (x *EvaluateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drone_control_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAccessRequest.ProtoReflect.Descriptor instead.
func (*EvaluateAccessRequest) Descriptor() ([]byte, []int) {
	return file_drone_control_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluateAccessRequest) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

var File_drone_control_proto protoreflect.FileDescriptor

var file_drone_control_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x22, 0x38, 0x0a, 0x0c, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x12,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x22,
	0x4b, 0x0a, 0x14, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x6f, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x72, 0x6f, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x76, 0x0a, 0x1e,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x57, 0x69, 0x74,
	0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x5f, 0x6a, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x75, 0x74, 0x6f, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x18, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x73,
	0x6f, 0x6e, 0x32, 0xc4, 0x05, 0x0a, 0x10, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x43, 0x6f, 0x72, 0x65, 0x12, 0x49, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x72,
	0x6f, 0x6e, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x6f,
	0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x72,
	0x6f, 0x6e, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x24, 0x2e, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x6f,
	0x6e, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0d,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x23, 0x2e,
	0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x65, 0x0a, 0x17, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2d, 0x2e, 0x64, 0x72, 0x6f,
	0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x6f, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x64, 0x72,
	0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x25, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x24, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64,
	0x72, 0x6f, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4a, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drone_control_proto_rawDescOnce sync.Once
	file_drone_control_proto_rawDescData = file_drone_control_proto_rawDesc
)

func file_drone_control_proto_rawDescGZIP() []byte {
	file_drone_control_proto_rawDescOnce.Do(func() {
		file_drone_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_drone_control_proto_rawDescData)
	})
	return file_drone_control_proto_rawDescData
}

var file_drone_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_drone_control_proto_goTypes = []interface{}{
	(*JsonResponse)(nil),                   // 0: drone_control.JsonResponse
	(*GetDronesRequest)(nil),               // 1: drone_control.GetDronesRequest
	(*GetDroneStatesRequest)(nil),          // 2: drone_control.GetDroneStatesRequest
	(*GetDroneDetailRequest)(nil),          // 3: drone_control.GetDroneDetailRequest
	(*FlightCommandRequest)(nil),           // 4: drone_control.FlightCommandRequest
	(*FlightCommandWithParamsRequest)(nil), // 5: drone_control.FlightCommandWithParamsRequest
	(*AutoFlightRequestReq)(nil),           // 6: drone_control.AutoFlightRequestReq
	(*GetFlightStatusRequest)(nil),         // 7: drone_control.GetFlightStatusRequest
	(*EvaluateAccessRequest)(nil),          // 8: drone_control.EvaluateAccessRequest
}
var file_drone_control_proto_depIdxs = []int32{
	1, // 0: drone_control.DroneControlCore.GetDrones:input_type -> drone_control.GetDronesRequest
	2, // 1: drone_control.DroneControlCore.GetDroneStates:input_type -> drone_control.GetDroneStatesRequest
	3, // 2: drone_control.DroneControlCore.GetDroneDetail:input_type -> drone_control.GetDroneDetailRequest
	4, // 3: drone_control.DroneControlCore.FlightCommand:input_type -> drone_control.FlightCommandRequest
	5, // 4: drone_control.DroneControlCore.FlightCommandWithParams:input_type -> drone_control.FlightCommandWithParamsRequest
	6, // 5: drone_control.DroneControlCore.AutoFlightRequest:input_type -> drone_control.AutoFlightRequestReq
	7, // 6: drone_control.DroneControlCore.GetFlightStatus:input_type -> drone_control.GetFlightStatusRequest
	8, // 7: drone_control.DroneControlCore.EvaluateAccess:input_type -> drone_control.EvaluateAccessRequest
	0, // 8: drone_control.DroneControlCore.GetDrones:output_type -> drone_control.JsonResponse
	0, // 9: drone_control.DroneControlCore.GetDroneStates:output_type -> drone_control.JsonResponse
	0, // 10: drone_control.DroneControlCore.GetDroneDetail:output_type -> drone_control.JsonResponse
	0, // 11: drone_control.DroneControlCore.FlightCommand:output_type -> drone_control.JsonResponse
	0, // 12: drone_control.DroneControlCore.FlightCommandWithParams:output_type -> drone_control.JsonResponse
	0, // 13: drone_control.DroneControlCore.AutoFlightRequest:output_type -> drone_control.JsonResponse
	0, // 14: drone_control.DroneControlCore.GetFlightStatus:output_type -> drone_control.JsonResponse
	0, // 15: drone_control.DroneControlCore.EvaluateAccess:output_type -> drone_control.JsonResponse
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drone_control_proto_init() }
func file_drone_control_proto_init() {
	if File_drone_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drone_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDronesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDroneStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDroneDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightCommandWithParamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoFlightRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drone_control_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drone_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drone_control_proto_goTypes,
		DependencyIndexes: file_drone_control_proto_depIdxs,
		MessageInfos:      file_drone_control_proto_msgTypes,
	}.Build()
	File_drone_control_proto = out.File
	file_drone_control_proto_rawDesc = nil
	file_drone_control_proto_goTypes = nil
	file_drone_control_proto_depIdxs = nil
}
