// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: drone_control.proto

package grpcpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DroneControlCore_GetDrones_FullMethodName               = "/drone_control.DroneControlCore/GetDrones"
	DroneControlCore_GetDroneStates_FullMethodName          = "/drone_control.DroneControlCore/GetDroneStates"
	DroneControlCore_GetDroneDetail_FullMethodName          = "/drone_control.DroneControlCore/GetDroneDetail"
	DroneControlCore_FlightCommand_FullMethodName           = "/drone_control.DroneControlCore/FlightCommand"
	DroneControlCore_FlightCommandWithParams_FullMethodName = "/drone_control.DroneControlCore/FlightCommandWithParams"
	DroneControlCore_AutoFlightRequest_FullMethodName       = "/drone_control.DroneControlCore/AutoFlightRequest"
	DroneControlCore_GetFlightStatus_FullMethodName         = "/drone_control.DroneControlCore/GetFlightStatus"
	DroneControlCore_EvaluateAccess_FullMethodName          = "/drone_control.DroneControlCore/EvaluateAccess"
	DroneControlCore_ConfirmMission_FullMethodName         = "/drone_control.DroneControlCore/ConfirmMission"
)

// DroneControlCoreClient is the client API for DroneControlCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneControlCoreClient interface {
	GetDrones(ctx context.Context, in *GetDronesRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetDroneStates(ctx context.Context, in *GetDroneStatesRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetDroneDetail(ctx context.Context, in *GetDroneDetailRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	FlightCommand(ctx context.Context, in *FlightCommandRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	FlightCommandWithParams(ctx context.Context, in *FlightCommandWithParamsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	AutoFlightRequest(ctx context.Context, in *AutoFlightRequestReq, opts ...grpc.CallOption) (*JsonResponse, error)
	GetFlightStatus(ctx context.Context, in *GetFlightStatusRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	EvaluateAccess(ctx context.Context, in *EvaluateAccessRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	ConfirmMission(ctx context.Context, in *GetDroneDetailRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type droneControlCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneControlCoreClient(cc grpc.ClientConnInterface) DroneControlCoreClient {
	return &droneControlCoreClient{cc}
}

func (c *droneControlCoreClient) GetDrones(ctx context.Context, in *GetDronesRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_GetDrones_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) GetDroneStates(ctx context.Context, in *GetDroneStatesRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_GetDroneStates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) GetDroneDetail(ctx context.Context, in *GetDroneDetailRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_GetDroneDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) FlightCommand(ctx context.Context, in *FlightCommandRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_FlightCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) FlightCommandWithParams(ctx context.Context, in *FlightCommandWithParamsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_FlightCommandWithParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) AutoFlightRequest(ctx context.Context, in *AutoFlightRequestReq, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_AutoFlightRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) GetFlightStatus(ctx context.Context, in *GetFlightStatusRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_GetFlightStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) EvaluateAccess(ctx context.Context, in *EvaluateAccessRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_EvaluateAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneControlCoreClient) ConfirmMission(ctx context.Context, in *GetDroneDetailRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, DroneControlCore_ConfirmMission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroneControlCoreServer is the server API for DroneControlCore service.
// All implementations must embed UnimplementedDroneControlCoreServer
// for forward compatibility
type DroneControlCoreServer interface {
	GetDrones(context.Context, *GetDronesRequest) (*JsonResponse, error)
	GetDroneStates(context.Context, *GetDroneStatesRequest) (*JsonResponse, error)
	GetDroneDetail(context.Context, *GetDroneDetailRequest) (*JsonResponse, error)
	FlightCommand(context.Context, *FlightCommandRequest) (*JsonResponse, error)
	FlightCommandWithParams(context.Context, *FlightCommandWithParamsRequest) (*JsonResponse, error)
	AutoFlightRequest(context.Context, *AutoFlightRequestReq) (*JsonResponse, error)
	GetFlightStatus(context.Context, *GetFlightStatusRequest) (*JsonResponse, error)
	EvaluateAccess(context.Context, *EvaluateAccessRequest) (*JsonResponse, error)
	mustEmbedUnimplementedDroneControlCoreServer()
}

// UnimplementedDroneControlCoreServer must be embedded to have forward compatible implementations.
type UnimplementedDroneControlCoreServer struct {
}

func (UnimplementedDroneControlCoreServer) GetDrones(context.Context, *GetDronesRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrones not implemented")
}
func (UnimplementedDroneControlCoreServer) GetDroneStates(context.Context, *GetDroneStatesRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDroneStates not implemented")
}
func (UnimplementedDroneControlCoreServer) GetDroneDetail(context.Context, *GetDroneDetailRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDroneDetail not implemented")
}
func (UnimplementedDroneControlCoreServer) FlightCommand(context.Context, *FlightCommandRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlightCommand not implemented")
}
func (UnimplementedDroneControlCoreServer) FlightCommandWithParams(context.Context, *FlightCommandWithParamsRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlightCommandWithParams not implemented")
}
func (UnimplementedDroneControlCoreServer) AutoFlightRequest(context.Context, *AutoFlightRequestReq) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoFlightRequest not implemented")
}
func (UnimplementedDroneControlCoreServer) GetFlightStatus(context.Context, *GetFlightStatusRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightStatus not implemented")
}
func (UnimplementedDroneControlCoreServer) EvaluateAccess(context.Context, *EvaluateAccessRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateAccess not implemented")
}
func (UnimplementedDroneControlCoreServer) mustEmbedUnimplementedDroneControlCoreServer() {}

// UnsafeDroneControlCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneControlCoreServer will
// result in compilation errors.
type UnsafeDroneControlCoreServer interface {
	mustEmbedUnimplementedDroneControlCoreServer()
}

func RegisterDroneControlCoreServer(s grpc.ServiceRegistrar, srv DroneControlCoreServer) {
	s.RegisterService(&DroneControlCore_ServiceDesc, srv)
}

func _DroneControlCore_GetDrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDronesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).GetDrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_GetDrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).GetDrones(ctx, req.(*GetDronesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_GetDroneStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDroneStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).GetDroneStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_GetDroneStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).GetDroneStates(ctx, req.(*GetDroneStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_GetDroneDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDroneDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).GetDroneDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_GetDroneDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).GetDroneDetail(ctx, req.(*GetDroneDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_FlightCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).FlightCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_FlightCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).FlightCommand(ctx, req.(*FlightCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_FlightCommandWithParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightCommandWithParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).FlightCommandWithParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_FlightCommandWithParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).FlightCommandWithParams(ctx, req.(*FlightCommandWithParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_AutoFlightRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoFlightRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).AutoFlightRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_AutoFlightRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).AutoFlightRequest(ctx, req.(*AutoFlightRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_GetFlightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).GetFlightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_GetFlightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).GetFlightStatus(ctx, req.(*GetFlightStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneControlCore_EvaluateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneControlCoreServer).EvaluateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneControlCore_EvaluateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneControlCoreServer).EvaluateAccess(ctx, req.(*EvaluateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DroneControlCore_ServiceDesc is the grpc.ServiceDesc for DroneControlCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneControlCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone_control.DroneControlCore",
	HandlerType: (*DroneControlCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDrones",
			Handler:    _DroneControlCore_GetDrones_Handler,
		},
		{
			MethodName: "GetDroneStates",
			Handler:    _DroneControlCore_GetDroneStates_Handler,
		},
		{
			MethodName: "GetDroneDetail",
			Handler:    _DroneControlCore_GetDroneDetail_Handler,
		},
		{
			MethodName: "FlightCommand",
			Handler:    _DroneControlCore_FlightCommand_Handler,
		},
		{
			MethodName: "FlightCommandWithParams",
			Handler:    _DroneControlCore_FlightCommandWithParams_Handler,
		},
		{
			MethodName: "AutoFlightRequest",
			Handler:    _DroneControlCore_AutoFlightRequest_Handler,
		},
		{
			MethodName: "GetFlightStatus",
			Handler:    _DroneControlCore_GetFlightStatus_Handler,
		},
		{
			MethodName: "EvaluateAccess",
			Handler:    _DroneControlCore_EvaluateAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drone_control.proto",
}
